### ISSUE TITLE
Crash when you rotate the screen

### ISSUE THREAD

**Issue by ryenyuku** [martin640/PartyCast#2]
When you rotates the screen, the app will crash. hidepain

**Comment by martin640** [comment]
Issue was caused by fragment trying to unbind null Unbinder, however I will force portrait orientation as landscape breaks also other stuff.

**Comment by martin640** [comment]
Fixed in https://github.com/martin640/PartyCast/commit/20e61d7e3f78c894444459650a72ff3e9250a98d
